name: Trigger Curl Requests from URL File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  curl_requests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read and trigger curl requests from urls.txt
      run: |
        while IFS= read -r url; do
          timestamp=$(date "+%H:%M:%S")
          response_code=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          echo "[$timestamp] Request for $url: $response_code"
          sleep 1.00  # Delay of 1000ms
        done < endpoints.txt
