name: Request Generator - On Demand

on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Make a curl request
      run: |
        response = $(curl http://petapi.lab-sec.f5demos.com/api/CatLookup/GetAllCats -header "Accept= application/json")         
        echo "response from curl= $response"
