name: Trigger Curl Requests from URL File

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  curl_requests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read and trigger curl requests from urls.txt
      run: |
        while IFS=' ' read -r method url; do
          timestamp=$(TZ="America/Los_Angeles" date "+%H:%M:%S")
          response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$url")
          echo "[$timestamp PST] Request for $url : $response_code"
          sleep 1.00  # Delay of 1000ms
        done < endpoints.txt
