name: Curl Requests for PetAPI Traffic Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  curl_requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Requests via Curl
      run: |
        # Curl Job Block
        while IFS='|' read -r method url body; do
          timestamp=$(TZ="America/Los_Angeles" date "+%H:%M:%S")

          # Encode only spaces in the URL
          encoded_url="${url// /%20}"

          # Check if URL ends with /JWT
          if [[ "$encoded_url" == */JWT ]]; then
            response=$(curl -s -X "$method" "$encoded_url" -H "Content-Type: application/json" -d "$body")
            token=$(echo "$response" | jq -r '.token')  # Extract the token value from the response
            echo "[$timestamp PST] $method to $encoded_url : $response_code"
            echo "Token variable created"
            continue
          fi

          # Prepare the curl command for /Submit/ endpoints
          if [[ "$encoded_url" == */Update ]]; then
            response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$encoded_url" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -d "$body")
            echo "[$timestamp PST] $method to $encoded_url : $response_code"
          else
            # For all other methods
            if [[ "$method" == "POST" || "$method" == "PUT" ]]; then
              response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$encoded_url" -H "Content-Type: application/json" -d "$body")
            else
              response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$encoded_url")
            fi
            echo "[$timestamp PST] $method to $encoded_url : $response_code"
          fi

          sleep 1  # Delay of 1 second
        done < endpoints.txt
