name: Trigger Curl Requests with JWT Token and Conditional Authorization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  curl_requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read and trigger curl requests from endpoints.txt with methods, POST/PUT body, and JWT token
      run: |
        token=""
        while IFS=' | ' read -r method url body; do
          timestamp=$(TZ="America/Los_Angeles" date "+%H:%M:%S")
          
          # Check if URL ends with /jwt
          if [[ "$url" == */JWT ]]; then
            response=$(curl -s -X "$method" "$url" -H "Content-Type: application/json" -d "$body")
            token=$(echo "$response" | jq -r '.token')  # Extract the token value from the response
            echo "[$timestamp PST] $method to $url : $response_code"
            continue
          fi

          # Prepare the curl command for /Submit/ endpoints
          if [[ "$url" == */Update ]]; then
            response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$url" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -d "$body")
            echo "[$timestamp PST] $method to $url : $response_code"
          else
            # For all other methods
            if [[ "$method" == "POST" || "$method" == "PUT" ]]; then
              response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$url" -H "Content-Type: application/json" -d "$body")
            else
            echo "$url"
              response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "$method" "$url")
            fi
            echo "[$timestamp PST] $method to $url : $response_code"
          fi

          sleep 1  # Delay of 1 second
        done < endpoints.txt
