name: Trigger Curl Requests with JWT Token and Conditional Authorization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  curl_requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read and trigger curl requests from endpoints.txt with methods, POST/PUT body, and JWT token
      run: |
            
            response_code=$(curl -o /dev/null -s -w "%{http_code}" -X "GET" -url "http://petapi.lab-sec.f5demos.com/api/CatLookup/GetByBreed?breed=Main Coon" -H "Content-Type: application/json")
            echo "[$timestamp PST] : $response_code"
