name: Curl Action

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  curl-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run curl command and get response code
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "http://petapi.lab-sec.f5demos.com/api/CatLookup/GetByBreed?breed=Main Coon")
          echo "HTTP Response Code: $response"
